#![allow(dead_code)]

use crate::{DType, Device, Shape, Tensor, TensorError};
use crossbeam::queue::SegQueue;
use dashmap::DashMap;
use std::{
    fmt::Display,
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    },
};

static NEXT_TENSOR_ID: AtomicUsize = AtomicUsize::new(1);

/// Stable identifier for a tensor node in Nove's computation graph.
///
/// # Notes
/// Tensor ids are generated by Nove when tensors are created or when tensor
/// operations produce new graph nodes. They are useful for debugging graph
/// structure without exposing backend storage internals.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TensorId(usize);

impl TensorId {
    pub(crate) fn next() -> Self {
        Self(NEXT_TENSOR_ID.fetch_add(1, Ordering::Relaxed))
    }
}

impl Display for TensorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Operation recorded for a graph node.
///
/// # Notes
/// `OpKind` stores the forward operation and any metadata needed by Nove's
/// autograd traversal. Backend implementations only compute forward storage;
/// gradient traversal is owned by Nove.
#[derive(Debug, Clone, PartialEq)]
pub enum OpKind {
    /// A tensor with no recorded parents.
    Leaf,
    /// A tensor cloned from another tensor.
    Clone,
    /// A tensor detached from its parents.
    Detach,
    /// A node produced when toggling gradient tracking.
    RequireGrad,
    /// A node representing a stored gradient tensor.
    Gradient,
    /// A zero-filled tensor matching another tensor.
    ZerosLike,
    /// A one-filled tensor matching another tensor.
    OnesLike,
    /// A comparison operation that does not currently participate in gradients.
    Comparison(&'static str),
    /// Elementwise addition.
    Add,
    /// Elementwise subtraction.
    Sub,
    /// Elementwise multiplication.
    Mul,
    /// Elementwise division.
    Div,
    /// Matrix multiplication.
    Matmul,
    /// Elementwise tensor exponentiation.
    Pow,
    /// Elementwise scalar exponentiation.
    Powf(f64),
    /// Elementwise negation.
    Neg,
    /// Elementwise square root.
    Sqrt,
    /// Elementwise reciprocal.
    Recip,
    /// Elementwise absolute value.
    Abs,
    /// Elementwise exponential.
    Exp,
    /// Elementwise natural logarithm.
    Log,
    /// Elementwise hyperbolic tangent.
    Tanh,
    /// Rectified linear activation.
    Relu,
    /// Sigmoid linear activation.
    Silu,
    /// Gaussian error linear activation.
    Gelu,
    /// Elementwise clipping.
    Clip {
        /// Lower clamp bound.
        min: f64,
        /// Upper clamp bound.
        max: f64,
    },
    /// Elementwise affine transform.
    Affine {
        /// Multiplicative weight.
        weight: f64,
        /// Additive bias.
        bias: f64,
    },
    /// Shape-only reshape operation.
    Reshape {
        /// Input shape before reshape.
        from: Shape,
        /// Output shape after reshape.
        to: Shape,
    },
    /// Broadcast operation.
    BroadcastAs {
        /// Input shape before broadcasting.
        from: Shape,
        /// Output shape after broadcasting.
        to: Shape,
    },
    /// Dimension swap.
    Transpose {
        /// First dimension.
        dim0: usize,
        /// Second dimension.
        dim1: usize,
    },
    /// Arbitrary dimension permutation.
    Permute {
        /// Forward permutation dimensions.
        dims: Vec<usize>,
        /// Inverse permutation dimensions used by backward traversal.
        inverse_dims: Vec<usize>,
    },
    /// Narrow slice along one dimension.
    Narrow {
        /// Original input shape.
        input_shape: Shape,
        /// Dimension being sliced.
        dim: usize,
        /// Start offset.
        start: usize,
        /// Slice length.
        length: usize,
    },
    /// Gather operation.
    Gather {
        /// Dimension used for gather.
        dim: usize,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Index selection operation.
    IndexSelect {
        /// Dimension used for index selection.
        dim: usize,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Embedding lookup.
    Embedding {
        /// Embedding table shape.
        table_shape: Shape,
    },
    /// Tensor stack operation.
    Stack {
        /// Inserted dimension.
        dim: usize,
        /// Shapes of all input tensors.
        input_shapes: Vec<Shape>,
    },
    /// Tensor concatenation operation.
    Cat {
        /// Concatenated dimension.
        dim: usize,
        /// Shapes of all input tensors.
        input_shapes: Vec<Shape>,
    },
    /// Conditional selection operation.
    WhereCond,
    /// Sum reduction.
    Sum {
        /// Optional axis and keepdim flag.
        axis: Option<(usize, bool)>,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Max reduction.
    Max {
        /// Optional axis and keepdim flag.
        axis: Option<(usize, bool)>,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Min reduction.
    Min {
        /// Optional axis and keepdim flag.
        axis: Option<(usize, bool)>,
        /// Original input shape.
        input_shape: Shape,
    },
    /// One-dimensional convolution.
    Conv1d {
        /// Padding size.
        padding: usize,
        /// Stride size.
        stride: usize,
        /// Dilation size.
        dilation: usize,
        /// Group count.
        groups: usize,
        /// Original input shape.
        input_shape: Shape,
        /// Kernel shape.
        kernel_shape: Shape,
    },
    /// Two-dimensional convolution.
    Conv2d {
        /// Padding size.
        padding: usize,
        /// Stride size.
        stride: usize,
        /// Dilation size.
        dilation: usize,
        /// Group count.
        groups: usize,
        /// Original input shape.
        input_shape: Shape,
        /// Kernel shape.
        kernel_shape: Shape,
    },
    /// One-dimensional max pooling.
    MaxPool1d {
        /// Kernel size.
        kernel_size: usize,
        /// Stride size.
        stride: usize,
        /// Original input shape.
        input_shape: Shape,
    },
    /// One-dimensional average pooling.
    AvgPool1d {
        /// Kernel size.
        kernel_size: usize,
        /// Stride size.
        stride: usize,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Two-dimensional max pooling.
    MaxPool2d {
        /// Kernel height and width.
        kernel_size: (usize, usize),
        /// Stride height and width.
        stride: (usize, usize),
        /// Original input shape.
        input_shape: Shape,
    },
    /// Two-dimensional average pooling.
    AvgPool2d {
        /// Kernel height and width.
        kernel_size: (usize, usize),
        /// Stride height and width.
        stride: (usize, usize),
        /// Original input shape.
        input_shape: Shape,
    },
    /// Mean reduction.
    Mean {
        /// Optional axis and keepdim flag.
        axis: Option<(usize, bool)>,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Variance reduction.
    Var {
        /// Reduced dimension.
        dim: usize,
        /// Whether to keep the reduced dimension.
        keep_dim: bool,
        /// Whether to use the unbiased variance estimate.
        unbiased: bool,
        /// Original input shape.
        input_shape: Shape,
    },
    /// Argmax reduction.
    ArgMax,
    /// Argmin reduction.
    ArgMin,
    /// Device transfer operation.
    ToDevice {
        /// Source device.
        from: Device,
        /// Target device.
        to: Device,
    },
    /// Dtype cast operation.
    ToDType {
        /// Source dtype.
        from: DType,
        /// Target dtype.
        to: DType,
    },
}

/// Directed edge from an operation node to one parent tensor.
///
/// # Notes
/// `GraphEdge` is lightweight graph metadata used by traversal helpers. Tensor
/// ownership remains on the graph node itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphEdge {
    /// Parent tensor id.
    pub parent: TensorId,
}

/// Nove-owned graph metadata for a tensor.
#[derive(Debug, Clone)]
pub(crate) struct GraphNode {
    pub(crate) id: TensorId,
    pub(crate) op: OpKind,
    pub(crate) parents: Vec<Tensor>,
}

impl GraphNode {
    pub(crate) fn new(op: OpKind, parents: Vec<Tensor>) -> Self {
        Self {
            id: TensorId::next(),
            op,
            parents,
        }
    }

    pub(crate) fn leaf() -> Self {
        Self::new(OpKind::Leaf, vec![])
    }

    pub(crate) fn clear_parents(&mut self) {
        self.parents.clear();
    }
}

impl Tensor {
    /// Returns this tensor's graph id.
    ///
    /// # Returns
    /// * `Ok(TensorId)` - The stable id assigned to this tensor's graph node.
    /// * `Err(TensorError)` - The error when reading tensor metadata fails.
    ///
    /// # Examples
    /// ```
    /// use nove::tensor::{Shape, Tensor};
    ///
    /// let device = if cfg!(feature = "candle-cpu") {
    ///     nove::device::candle::cpu().unwrap()
    /// } else {
    ///     nove::device::native::cpu().unwrap()
    /// };
    /// let tensor = Tensor::from_slice(&[1.0f32, 2.0], &Shape::from_dims(&[2]), &device, false).unwrap();
    ///
    /// let first = tensor.graph_id().unwrap();
    /// let second = tensor.graph_id().unwrap();
    ///
    /// assert_eq!(first, second);
    /// ```
    pub fn graph_id(&self) -> Result<TensorId, TensorError> {
        Ok(self.data.read()?.graph.id)
    }

    /// Detach the tensor from the computational graph.
    ///
    /// This creates a new tensor that shares the same data but is disconnected
    /// from the computational graph. The detached tensor will:
    /// - Have no parent tensors
    /// - Disconnect from the computational graph
    ///
    /// # Notes
    /// Detaching does not copy values into Candle autograd storage. Gradients
    /// stay represented by Nove graph metadata and Nove tensor values.
    ///
    /// # Returns
    /// * `Ok(Tensor)` - A new tensor detached from the computational graph.
    /// * `Err(TensorError)` - The error when detaching the tensor.
    ///
    /// # Examples
    /// ```
    /// use nove::tensor::{Shape, Tensor};
    ///
    /// let device = if cfg!(feature = "candle-cpu") {
    ///     nove::device::candle::cpu().unwrap()
    /// } else {
    ///     nove::device::native::cpu().unwrap()
    /// };
    /// let tensor = Tensor::from_slice(&[1.0f32, 2.0], &Shape::from_dims(&[2]), &device, true).unwrap();
    /// let detached = tensor.detach().unwrap();
    ///
    /// assert!(!detached.grad_enabled().unwrap());
    /// assert_eq!(detached.to_vec::<f32>().unwrap(), vec![1.0, 2.0]);
    /// ```
    pub fn detach(&self) -> Result<Tensor, TensorError> {
        let data = self.data.read()?;
        let storage = data.storage.detach()?;
        let device = data.device.clone();
        let grad = match &data.grad {
            Some(grad) => Some(grad.detach()?),
            None => None,
        };
        let name = data.name.clone();
        drop(data);

        Ok(Self::from_backend_parts(
            storage,
            device,
            false,
            vec![],
            OpKind::Detach,
            grad,
            name,
        ))
    }

    /// Clear the computational graph reachable from this tensor.
    ///
    /// # Notes
    /// This removes parent links from the current graph and any reachable
    /// gradient tensors. Tensor values and devices are left unchanged.
    ///
    /// # Returns
    /// * `Ok(())` - The tensor's computational graph is successfully cleared.
    /// * `Err(TensorError)` - The error when clearing the tensor's computational graph.
    ///
    /// # Examples
    /// ```
    /// use nove::tensor::{Shape, Tensor};
    ///
    /// let device = if cfg!(feature = "candle-cpu") {
    ///     nove::device::candle::cpu().unwrap()
    /// } else {
    ///     nove::device::native::cpu().unwrap()
    /// };
    /// let input = Tensor::from_slice(&[1.0f32, 2.0], &Shape::from_dims(&[2]), &device, true).unwrap();
    /// let output = input.add(&input).unwrap();
    ///
    /// output.clear_graph().unwrap();
    ///
    /// assert_eq!(output.to_vec::<f32>().unwrap(), vec![2.0, 4.0]);
    /// ```
    pub fn clear_graph(&self) -> Result<(), TensorError> {
        let queue = SegQueue::new();
        let visited = DashMap::new();

        queue.push(self.copy());
        visited.insert(Arc::as_ptr(&self.data) as usize, true);

        while let Some(current) = queue.pop() {
            let current_parents = {
                let mut data = current.data.write()?;
                if let Some(grad) = data.grad.as_ref() {
                    queue.push(grad.copy());
                }
                std::mem::take(&mut data.graph.parents)
            };

            for parent in current_parents {
                let parent_id = Arc::as_ptr(&parent.data) as usize;
                if visited.insert(parent_id, true).is_none() {
                    queue.push(parent);
                }
            }
        }

        Ok(())
    }
}
