//! The `dataloader` module defines the `Dataloader` trait and provides some
//! implemented data loader.

use crate::tensor::Device;

pub mod util;

/// The `Dataloader` trait defines the interface for a data loader.
/// Every data loader should implement this trait.
///
/// # Lifetime Parameters
/// * `'a` - The lifetime of the device.
///
/// # Required Type Parameters:
/// * `Output` - The type of the output data.
///
/// # Required Methods:
/// * `next` - Returns the next data.
/// * `reset` - Reset the dataloader to the initial state.
/// * `to_device` - Move the dataloader to the specified device.
pub trait Dataloader<'a> {
    /// The type of the output data.
    type Output;

    /// Returns the next data.
    ///
    /// Returns:
    /// * `Some(data)` - The next data.
    /// * `None` - There is no more data.
    fn next(&mut self) -> Option<Self::Output>;

    /// Reset the dataloader to the initial state.
    fn reset(&mut self);

    /// Move the dataloader to the specified device.
    /// The data generated by the `next` method would be on the specified device
    /// after calling this method.
    ///
    /// # Arguments
    /// * `device` - The device to move to.
    fn to_device(&mut self, device: &'a Device);
}
